package com.zifras.notificacion

public enum CodigoNotificacion {
	SIN_CAMPO,
	SIN_LOTE,
	SIN_CAMPANA,
	SIN_COTIZACION,
	SIN_CONFIGURACION,
	SIN_PROVEEDOR,
	SIN_HERRAMIENTA,
	SIN_EMPLEADO,
	SIN_SEMILLA,
	SIN_FERTILIZANTE,
	SIN_AGROQUIMICO,
	SIN_INSUMO,
	SIN_CLIENTE,
	SIN_PRECIO,
	SIN_STOCK_INSUMO,
	SIN_GALPON,
	SIN_PLAN,
	SIN_PRODUCCION,
	MES_PRUEBA_PREMIUM
}