---
grails:
    profile: web
    codegen:
        defaultPackage: zifras
    gorm:
        autowire: true
        multiTenancy:
            mode: DISCRIMINATOR
            tenantResolverClass: com.zifras.CurrentUserTenantResolver
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
        default.mapping: {
            id generator: 'org.hibernate.id.enhanced.SequenceStyleGenerator', params: [prefer_sequence_per_entity: true]
        }
    plugin:
        springsecurity:
          ui:
            encodePassword: false
            password:
              minLength: 8
              maxLength: 64
              validationRegex: '^.*(?=.*\\d)(?=.*[a-zA-Z])(?=.*[!@#$%^&]).*$'
            register:
              defaultRoleNames: ['ROLE_USER']
              emailFrom: '"Calim" <notificaciones@calim.com.ar>'
            forgotPassword.emailFrom: '"Calim" <notificaciones@calim.com.ar>'
          successHandler:
            defaultTargetUrl: "/start/index"
            alwaysUseDefault: false
            targetUrlParameter: 'spring-security-redirect'
            ajaxSuccessUrl: '/login/ajaxSuccess'
            successHandler.useReferer: false
    cors:
        enabled: true
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
        upload:
            maxFileSize: 52428800
            maxRequestSize: 52428800
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
    dialect: net.kaleidos.hibernate.PostgresqlExtensionsDialect
dataSource:
    pooled: true
    jmxExport: true
    #driverClassName: org.h2.Driver
    #username: sa
    #password: ''
    driverClassName: org.postgresql.Driver
    username: zeta
    password: zeta2017
    url: "jdbc:postgresql://localhost:5432/zifras"

environments:
    development:
        versionActualApp: 0.9
        marketLinkAndroid: "https://play.google.com/store/apps/details?id=com.calim.micontador"
        marketLinkIos: " "
        tokenFCM: "AAAA2CE3oWA:APA91bF-vnOWunUWlu-Cu9vDjtSYGPnzp3nGSuCdDVITV1F48yDuYEt3W7Hqrur_d_6nLavjhCi4Gdqr9ynCOYVe74ADTY-qmQ7X6-VHB721Xkhgzhxu6qdFhlAA42zfwVi7S0NAq1lp"
        carpetaArchivos: "archivosCalimDesarrollo"
        certificadoAfip: "workspace/zifras/src/main/resources/certificado2021.pfx"
        credencialesGoogle: "credentialsGoogle/credentials.json"
        serialNumberAfip: "CUIT 20282509009"
        wsPadronA5Afip: "https://awshomo.afip.gov.ar/sr-padron/webservices/personaServiceA5?WSDL"
        loginCmsAfip: 'https://wsaahomo.afip.gov.ar/ws/services/LoginCms'
        dataSource:
            dbCreate: update
            driverClassName: org.postgresql.Driver
            username: zeta
            password: zeta2017
            url: "jdbc:postgresql://localhost:5432/zifras"
        grails:
            serverURL: "http://localhost:8080"
    test:
        versionActualApp: 0.9
        marketLinkAndroid: "https://play.google.com/store/apps/details?id=com.calim.micontador"
        marketLinkIos: " "
        tokenFCM: "AAAA2CE3oWA:APA91bF-vnOWunUWlu-Cu9vDjtSYGPnzp3nGSuCdDVITV1F48yDuYEt3W7Hqrur_d_6nLavjhCi4Gdqr9ynCOYVe74ADTY-qmQ7X6-VHB721Xkhgzhxu6qdFhlAA42zfwVi7S0NAq1lp"
        carpetaArchivos: "archivosCalimDesarrollo"
        certificadoAfip: "certificadoAfip/certificadoCalim.pfx"
        credencialesGoogle: "credentialsGoogle/credentials.json"
        serialNumberAfip: "CUIT 20282509009"
        wsPadronA5Afip: "https://awshomo.afip.gov.ar/sr-padron/webservices/personaServiceA5?WSDL"
        dataSource:
            dbCreate: update
            driverClassName: org.postgresql.Driver
            username: zeta
            password: zeta2017
            url: "jdbc:postgresql://localhost:5432/zifras"
        grails:
            serverURL: "http://localhost:8080"
    production:
        versionActualApp: 0.9
        marketLinkAndroid: "https://play.google.com/store/apps/details?id=com.calim.micontador"
        marketLinkIos: " "
        tokenFCM: "AAAA2CE3oWA:APA91bF-vnOWunUWlu-Cu9vDjtSYGPnzp3nGSuCdDVITV1F48yDuYEt3W7Hqrur_d_6nLavjhCi4Gdqr9ynCOYVe74ADTY-qmQ7X6-VHB721Xkhgzhxu6qdFhlAA42zfwVi7S0NAq1lp"
        carpetaArchivos: "calimUploads"
        certificadoAfip: "certificadoAfip/certificado.pfx"
        credencialesGoogle: "credentialsGoogle/credentials.json"
        serialNumberAfip: "CUIT 30716783916"
        wsPadronA5Afip: "https://aws.afip.gov.ar/sr-padron/webservices/personaServiceA5?WSDL"
        loginCmsAfip: 'https://wsaa.afip.gov.ar/ws/services/LoginCms'
        dataSource:
            dbCreate: update
            driverClassName: org.postgresql.Driver
            username: zeta
            password: zeta2017
            url: "jdbc:postgresql://localhost:5432/zifras"
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
        grails:
            serverURL: "https://app.calim.com.ar"
